# Generated by Django 4.2.13 on 2024-08-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('summary', models.CharField(max_length=225)),
                ('linkedin', models.CharField(max_length=225)),
                ('university', models.CharField(max_length=225)),
                ('work', models.CharField(max_length=225)),
                ('skill', models.CharField(max_length=225)),
            ],
        ),
    ]
